name: Flake CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'flake.nix'

jobs:
  nix-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Check flake
        run: task nix:check-flake

      - name: Build package
        run: task nix:build-flake

      - name: Run and check package
        run: task nix:test-run-flake